spring:
  data:
    mongodb:
#      authentication-database: dbAdmin
      username: keepnote
      password: keepnote
      database: keepnote
      port: 27017
      host: 127.0.0.1
  application:
    name: reminderservice
server:
  port: 8081



#
#spring:
#  data:
#    mongodb:
# #     authentication-database:
#      username: chandan
#      password: root
#      database: reminderDb
#      port: 27017
#      host: localhost
#  application:
#    name: reminder-service
#
#server:
#  port: 8081
