spring:
  datasource:
    url: jdbc:mysql://localhost:3306/keepnote?verifyServerCertificate=false&useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    #dialect: org.hibernate.dialect.OracleDialect
server:
  port: 8089